### ISSUE TITLE
HostDependencies incorrect about CMake version

### ISSUE THREAD

**Issue by harvv** [SEL4PROJ/docs#36]
The current HostDependencies document advises the use of Ubuntu 18.04 in order to have an appropriately current version of CMake.
Ubuntu 18.04 's normal, out-of-the-box repositories (used by apt-get) install version 3.10.2
(at least as of the current date, July 30, 2019)

However, this version seems to be insufficient for building se4L4test.  Running init-build.sh:
...
CMake Error at projects/sel4runtime/CMakeLists.txt:20 (cmake_minimum_required):
  CMake 3.12.0 or higher is required.  You are running version 3.10.2

**Comment by kent-mcleod** [comment]
I updated the instructions to reflect the required CMake version.  Thanks for reporting
